#!/usr/bin/env fish

# Fish Shell Auto-Configuration
# This script sets up all necessary PATHs and tools
# Run once after installing Fish: fish fish-config.fish

echo "🐟 Setting up Fish shell configuration..."

# Determine Homebrew prefix (M1/M2 vs Intel)
if test -d /opt/homebrew
    set BREW_PREFIX /opt/homebrew
else
    set BREW_PREFIX /usr/local
end

# Create Fish config directory if it doesn't exist
mkdir -p ~/.config/fish

# Create config.fish
echo "📝 Creating ~/.config/fish/config.fish..."
cat > ~/.config/fish/config.fish << 'EOF'
# Fish Shell Configuration
# Auto-generated by mac-backup setup

# Homebrew
if test -d /opt/homebrew
    eval (/opt/homebrew/bin/brew shellenv)
else if test -d /usr/local
    eval (/usr/local/bin/brew shellenv)
end

# Python (pyenv)
if command -v pyenv > /dev/null
    pyenv init - | source
    pyenv virtualenv-init - | source
end

# Node.js (fnm)
if command -v fnm > /dev/null
    fnm env --use-on-cd | source
end

# PostgreSQL client (libpq)
if test -d $HOMEBREW_PREFIX/opt/libpq/bin
    fish_add_path $HOMEBREW_PREFIX/opt/libpq/bin
end

# Direnv
if command -v direnv > /dev/null
    direnv hook fish | source
end

# fzf (Fuzzy Finder)
if command -v fzf > /dev/null
    # Setup fzf key bindings (will be enhanced by fzf.fish plugin)
    fzf --fish | source
end

# zoxide (Smart cd)
if command -v zoxide > /dev/null
    zoxide init fish | source
end

# Custom bin directory
if test -d ~/bin
    fish_add_path ~/bin
end

# Editor
set -gx EDITOR vim

# Aliases
alias ll='ls -lah'
alias g='git'
alias dc='docker-compose'
alias d='docker'

# zoxide aliases
if command -v zoxide > /dev/null
    alias cd='z'  # Replace cd with zoxide
end

EOF

echo "✅ Fish config created"

# Install Fisher (Fish plugin manager)
echo ""
echo "📦 Installing Fisher plugin manager..."
if not functions -q fisher
    curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source
    fisher install jorgebucaran/fisher
    echo "✅ Fisher installed"
else
    echo "⚠️  Fisher already installed"
end

# Install Fish plugins
echo ""
echo "📦 Installing Fish plugins..."
echo ""

echo "  🌊 Installing Tide prompt..."
fisher install IlanCosman/tide@v6
echo "  ✅ Tide installed"

echo ""
echo "  🔍 Installing fzf.fish (fuzzy finder integration)..."
fisher install PatrickF1/fzf.fish
echo "  ✅ fzf.fish installed"

echo ""
echo "  🔔 Installing done (command notifications)..."
fisher install franciscolourenco/done
echo "  ✅ done installed"

echo ""
echo "🎉 Fish configuration complete!"
echo ""
echo "Installed plugins:"
echo "  ✅ Tide - Beautiful prompt with Python/Node version display"
echo "  ✅ fzf.fish - Fuzzy search (Ctrl+R for history, Ctrl+Alt+F for files)"
echo "  ✅ done - Notifications for long-running commands"
echo ""
echo "Enabled tools:"
echo "  ✅ zoxide - Smart directory jumper (use 'z' instead of 'cd')"
echo ""
echo "Next steps:"
echo "  1. Restart your terminal or run: exec fish"
echo "  2. Configure Tide prompt: tide configure"
echo "  3. Try: Ctrl+R to search command history!"
echo "  4. Try: z <directory-name> to jump to frequently used dirs"
echo ""
